// <auto-generated />
using System;
using BookingProcessor.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookingProcessor.Migrations
{
    [DbContext(typeof(BookingContext))]
    [Migration("20231122164556_AddedNewAirPort")]
    partial class AddedNewAirPort
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("BookingProcessor.Models.Airline", b =>
                {
                    b.Property<int>("AirlineID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AirlineName")
                        .HasColumnType("TEXT");

                    b.Property<string>("HQ")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<double>("Rating")
                        .HasColumnType("REAL");

                    b.HasKey("AirlineID");

                    b.ToTable("Airline");

                    b.HasData(
                        new
                        {
                            AirlineID = 1,
                            AirlineName = "Example Airline 1",
                            HQ = "London, England",
                            PhoneNumber = "123-456-7890",
                            Rating = 4.5
                        },
                        new
                        {
                            AirlineID = 2,
                            AirlineName = "Example Airline 2",
                            HQ = "France, Paris",
                            PhoneNumber = "987-654-3210",
                            Rating = 3.7999999999999998
                        },
                        new
                        {
                            AirlineID = 3,
                            AirlineName = "Example Airline 3",
                            HQ = "Moscow, Russia",
                            PhoneNumber = "555-123-4567",
                            Rating = 4.2000000000000002
                        },
                        new
                        {
                            AirlineID = 4,
                            AirlineName = "Example Airline 4",
                            HQ = "USA, LA",
                            PhoneNumber = "333-777-8888",
                            Rating = 3.5
                        },
                        new
                        {
                            AirlineID = 5,
                            AirlineName = "Example Airline 5",
                            HQ = "Japan, Tokyo",
                            PhoneNumber = "111-222-3333",
                            Rating = 4.0
                        });
                });

            modelBuilder.Entity("BookingProcessor.Models.Airport", b =>
                {
                    b.Property<int>("AirportID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AirportName")
                        .HasColumnType("TEXT");

                    b.Property<int>("CountryID")
                        .HasColumnType("INTEGER");

                    b.HasKey("AirportID");

                    b.ToTable("Airport");

                    b.HasData(
                        new
                        {
                            AirportID = 1,
                            AirportName = "Denver International Airport",
                            CountryID = 840
                        },
                        new
                        {
                            AirportID = 2,
                            AirportName = "Dubai International Airport",
                            CountryID = 784
                        },
                        new
                        {
                            AirportID = 3,
                            AirportName = "Beijing Internation Airport",
                            CountryID = 156
                        },
                        new
                        {
                            AirportID = 4,
                            AirportName = "Istanbul International Airport",
                            CountryID = 792
                        },
                        new
                        {
                            AirportID = 5,
                            AirportName = "Heathrow Airport",
                            CountryID = 826
                        },
                        new
                        {
                            AirportID = 6,
                            AirportName = "Indira Gandhi International Airport",
                            CountryID = 356
                        },
                        new
                        {
                            AirportID = 7,
                            AirportName = "Charles de Gaulle Airport",
                            CountryID = 250
                        },
                        new
                        {
                            AirportID = 8,
                            AirportName = "Amsterdam Airport Schiphol",
                            CountryID = 528
                        },
                        new
                        {
                            AirportID = 9,
                            AirportName = "Adolfo Suárez Madrid-Barajas Airport",
                            CountryID = 724
                        },
                        new
                        {
                            AirportID = 10,
                            AirportName = "Tokyo Haneda Airport",
                            CountryID = 392
                        },
                        new
                        {
                            AirportID = 11,
                            AirportName = "Frankfurt Airport",
                            CountryID = 276
                        },
                        new
                        {
                            AirportID = 12,
                            AirportName = "Mexico City International Airport",
                            CountryID = 484
                        },
                        new
                        {
                            AirportID = 13,
                            AirportName = "Soekarno-Hatta International Airport",
                            CountryID = 360
                        },
                        new
                        {
                            AirportID = 14,
                            AirportName = "Toronto Pearson International Airport",
                            CountryID = 124
                        },
                        new
                        {
                            AirportID = 15,
                            AirportName = "São Paulo/Guarulhos International Airport",
                            CountryID = 76
                        },
                        new
                        {
                            AirportID = 16,
                            AirportName = "Gatwick Airport",
                            CountryID = 826
                        });
                });

            modelBuilder.Entity("BookingProcessor.Models.Booking", b =>
                {
                    b.Property<int>("BookingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CountryID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FlightID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HotelBookingID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InsuranceBookingID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("VehicleBookingID")
                        .HasColumnType("INTEGER");

                    b.HasKey("BookingID");

                    b.ToTable("Booking");

                    b.HasData(
                        new
                        {
                            BookingID = 1,
                            ClientID = 1,
                            CountryID = 826,
                            FlightID = 1,
                            HotelBookingID = 1,
                            InsuranceBookingID = 1,
                            PurchaseDate = new DateTime(2023, 11, 22, 16, 45, 56, 655, DateTimeKind.Local).AddTicks(9834),
                            VehicleBookingID = 1
                        },
                        new
                        {
                            BookingID = 2,
                            ClientID = 2,
                            CountryID = 826,
                            FlightID = 2,
                            HotelBookingID = 2,
                            InsuranceBookingID = 2,
                            PurchaseDate = new DateTime(2023, 11, 22, 16, 45, 56, 655, DateTimeKind.Local).AddTicks(9876),
                            VehicleBookingID = 2
                        },
                        new
                        {
                            BookingID = 3,
                            ClientID = 3,
                            CountryID = 826,
                            FlightID = 3,
                            HotelBookingID = 3,
                            InsuranceBookingID = 3,
                            PurchaseDate = new DateTime(2023, 11, 22, 16, 45, 56, 655, DateTimeKind.Local).AddTicks(9879),
                            VehicleBookingID = 3
                        },
                        new
                        {
                            BookingID = 4,
                            ClientID = 4,
                            CountryID = 826,
                            FlightID = 4,
                            HotelBookingID = 4,
                            InsuranceBookingID = 4,
                            PurchaseDate = new DateTime(2023, 11, 22, 16, 45, 56, 655, DateTimeKind.Local).AddTicks(9880),
                            VehicleBookingID = 4
                        },
                        new
                        {
                            BookingID = 5,
                            ClientID = 5,
                            CountryID = 826,
                            FlightID = 5,
                            HotelBookingID = 5,
                            InsuranceBookingID = 5,
                            PurchaseDate = new DateTime(2023, 11, 22, 16, 45, 56, 655, DateTimeKind.Local).AddTicks(9882),
                            VehicleBookingID = 5
                        });
                });

            modelBuilder.Entity("BookingProcessor.Models.Client", b =>
                {
                    b.Property<int>("ClientID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.HasKey("ClientID");

                    b.ToTable("Client");

                    b.HasData(
                        new
                        {
                            ClientID = 1,
                            BirthDate = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "john.doe@example.com",
                            FirstName = "John",
                            LastName = "Doe",
                            PhoneNumber = "123-456-7890"
                        },
                        new
                        {
                            ClientID = 2,
                            BirthDate = new DateTime(1985, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jane.smith@example.com",
                            FirstName = "Jane",
                            LastName = "Smith",
                            PhoneNumber = "987-654-3210"
                        },
                        new
                        {
                            ClientID = 3,
                            BirthDate = new DateTime(1992, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "alice.johnson@example.com",
                            FirstName = "Alice",
                            LastName = "Johnson",
                            PhoneNumber = "555-123-4567"
                        },
                        new
                        {
                            ClientID = 4,
                            BirthDate = new DateTime(1980, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "bob.anderson@example.com",
                            FirstName = "Bob",
                            LastName = "Anderson",
                            PhoneNumber = "333-777-8888"
                        },
                        new
                        {
                            ClientID = 5,
                            BirthDate = new DateTime(1988, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "eva.williams@example.com",
                            FirstName = "Eva",
                            LastName = "Williams",
                            PhoneNumber = "111-222-3333"
                        });
                });

            modelBuilder.Entity("BookingProcessor.Models.Country", b =>
                {
                    b.Property<int>("CountryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CountryName")
                        .HasColumnType("TEXT");

                    b.HasKey("CountryID");

                    b.ToTable("Country");

                    b.HasData(
                        new
                        {
                            CountryID = 4,
                            CountryName = "Afghanistan"
                        },
                        new
                        {
                            CountryID = 8,
                            CountryName = "Albania"
                        },
                        new
                        {
                            CountryID = 12,
                            CountryName = "Algeria"
                        },
                        new
                        {
                            CountryID = 16,
                            CountryName = "American Samoa"
                        },
                        new
                        {
                            CountryID = 20,
                            CountryName = "Andorra"
                        },
                        new
                        {
                            CountryID = 24,
                            CountryName = "Angola"
                        },
                        new
                        {
                            CountryID = 660,
                            CountryName = "Anguilla"
                        },
                        new
                        {
                            CountryID = 10,
                            CountryName = "Antarctica"
                        },
                        new
                        {
                            CountryID = 28,
                            CountryName = "Antigua and Barbuda"
                        },
                        new
                        {
                            CountryID = 32,
                            CountryName = "Argentina"
                        },
                        new
                        {
                            CountryID = 51,
                            CountryName = "Armenia"
                        },
                        new
                        {
                            CountryID = 533,
                            CountryName = "Aruba"
                        },
                        new
                        {
                            CountryID = 36,
                            CountryName = "Australia"
                        },
                        new
                        {
                            CountryID = 40,
                            CountryName = "Austria"
                        },
                        new
                        {
                            CountryID = 31,
                            CountryName = "Azerbaijan"
                        },
                        new
                        {
                            CountryID = 44,
                            CountryName = "Bahamas"
                        },
                        new
                        {
                            CountryID = 48,
                            CountryName = "Bahrain"
                        },
                        new
                        {
                            CountryID = 50,
                            CountryName = "Bangladesh"
                        },
                        new
                        {
                            CountryID = 52,
                            CountryName = "Barbados"
                        },
                        new
                        {
                            CountryID = 112,
                            CountryName = "Belarus"
                        },
                        new
                        {
                            CountryID = 56,
                            CountryName = "Belgium"
                        },
                        new
                        {
                            CountryID = 84,
                            CountryName = "Belize"
                        },
                        new
                        {
                            CountryID = 204,
                            CountryName = "Benin"
                        },
                        new
                        {
                            CountryID = 60,
                            CountryName = "Bermuda"
                        },
                        new
                        {
                            CountryID = 64,
                            CountryName = "Bhutan"
                        },
                        new
                        {
                            CountryID = 68,
                            CountryName = "Bolivia, Plurinational State of"
                        },
                        new
                        {
                            CountryID = 535,
                            CountryName = "Bonaire, Sint Eustatius and Saba"
                        },
                        new
                        {
                            CountryID = 70,
                            CountryName = "Bosnia and Herzegovina"
                        },
                        new
                        {
                            CountryID = 72,
                            CountryName = "Botswana"
                        },
                        new
                        {
                            CountryID = 74,
                            CountryName = "Bouvet Island"
                        },
                        new
                        {
                            CountryID = 76,
                            CountryName = "Brazil"
                        },
                        new
                        {
                            CountryID = 86,
                            CountryName = "British Indian Ocean Territory"
                        },
                        new
                        {
                            CountryID = 96,
                            CountryName = "Brunei Darussalam"
                        },
                        new
                        {
                            CountryID = 100,
                            CountryName = "Bulgaria"
                        },
                        new
                        {
                            CountryID = 854,
                            CountryName = "Burkina Faso"
                        },
                        new
                        {
                            CountryID = 108,
                            CountryName = "Burundi"
                        },
                        new
                        {
                            CountryID = 132,
                            CountryName = "Cabo Verde"
                        },
                        new
                        {
                            CountryID = 116,
                            CountryName = "Cambodia"
                        },
                        new
                        {
                            CountryID = 120,
                            CountryName = "Cameroon"
                        },
                        new
                        {
                            CountryID = 124,
                            CountryName = "Canada"
                        },
                        new
                        {
                            CountryID = 136,
                            CountryName = "Cayman Islands"
                        },
                        new
                        {
                            CountryID = 140,
                            CountryName = "Central African Republic"
                        },
                        new
                        {
                            CountryID = 148,
                            CountryName = "Chad"
                        },
                        new
                        {
                            CountryID = 152,
                            CountryName = "Chile"
                        },
                        new
                        {
                            CountryID = 156,
                            CountryName = "China"
                        },
                        new
                        {
                            CountryID = 162,
                            CountryName = "Christmas Island"
                        },
                        new
                        {
                            CountryID = 166,
                            CountryName = "Cocos (Keeling) Islands"
                        },
                        new
                        {
                            CountryID = 170,
                            CountryName = "Colombia"
                        },
                        new
                        {
                            CountryID = 174,
                            CountryName = "Comoros"
                        },
                        new
                        {
                            CountryID = 178,
                            CountryName = "Congo"
                        },
                        new
                        {
                            CountryID = 180,
                            CountryName = "Congo, the Democratic Republic of the"
                        },
                        new
                        {
                            CountryID = 184,
                            CountryName = "Cook Islands"
                        },
                        new
                        {
                            CountryID = 188,
                            CountryName = "Costa Rica"
                        },
                        new
                        {
                            CountryID = 384,
                            CountryName = "Côte d'Ivoire"
                        },
                        new
                        {
                            CountryID = 191,
                            CountryName = "Croatia"
                        },
                        new
                        {
                            CountryID = 192,
                            CountryName = "Cuba"
                        },
                        new
                        {
                            CountryID = 531,
                            CountryName = "Curaçao"
                        },
                        new
                        {
                            CountryID = 196,
                            CountryName = "Cyprus"
                        },
                        new
                        {
                            CountryID = 203,
                            CountryName = "Czechia"
                        },
                        new
                        {
                            CountryID = 208,
                            CountryName = "Denmark"
                        },
                        new
                        {
                            CountryID = 262,
                            CountryName = "Djibouti"
                        },
                        new
                        {
                            CountryID = 212,
                            CountryName = "Dominica"
                        },
                        new
                        {
                            CountryID = 214,
                            CountryName = "Dominican Republic"
                        },
                        new
                        {
                            CountryID = 218,
                            CountryName = "Ecuador"
                        },
                        new
                        {
                            CountryID = 818,
                            CountryName = "Egypt"
                        },
                        new
                        {
                            CountryID = 222,
                            CountryName = "El Salvador"
                        },
                        new
                        {
                            CountryID = 226,
                            CountryName = "Equatorial Guinea"
                        },
                        new
                        {
                            CountryID = 232,
                            CountryName = "Eritrea"
                        },
                        new
                        {
                            CountryID = 233,
                            CountryName = "Estonia"
                        },
                        new
                        {
                            CountryID = 748,
                            CountryName = "Eswatini"
                        },
                        new
                        {
                            CountryID = 231,
                            CountryName = "Ethiopia"
                        },
                        new
                        {
                            CountryID = 238,
                            CountryName = "Falkland Islands (Malvinas)"
                        },
                        new
                        {
                            CountryID = 234,
                            CountryName = "Faroe Islands"
                        },
                        new
                        {
                            CountryID = 242,
                            CountryName = "Fiji"
                        },
                        new
                        {
                            CountryID = 246,
                            CountryName = "Finland"
                        },
                        new
                        {
                            CountryID = 250,
                            CountryName = "France"
                        },
                        new
                        {
                            CountryID = 254,
                            CountryName = "French Guiana"
                        },
                        new
                        {
                            CountryID = 258,
                            CountryName = "French Polynesia"
                        },
                        new
                        {
                            CountryID = 260,
                            CountryName = "French Southern Territories"
                        },
                        new
                        {
                            CountryID = 266,
                            CountryName = "Gabon"
                        },
                        new
                        {
                            CountryID = 270,
                            CountryName = "Gambia"
                        },
                        new
                        {
                            CountryID = 268,
                            CountryName = "Georgia"
                        },
                        new
                        {
                            CountryID = 276,
                            CountryName = "Germany"
                        },
                        new
                        {
                            CountryID = 288,
                            CountryName = "Ghana"
                        },
                        new
                        {
                            CountryID = 292,
                            CountryName = "Gibraltar"
                        },
                        new
                        {
                            CountryID = 300,
                            CountryName = "Greece"
                        },
                        new
                        {
                            CountryID = 304,
                            CountryName = "Greenland"
                        },
                        new
                        {
                            CountryID = 308,
                            CountryName = "Grenada"
                        },
                        new
                        {
                            CountryID = 312,
                            CountryName = "Guadeloupe"
                        },
                        new
                        {
                            CountryID = 316,
                            CountryName = "Guam"
                        },
                        new
                        {
                            CountryID = 320,
                            CountryName = "Guatemala"
                        },
                        new
                        {
                            CountryID = 831,
                            CountryName = "Guernsey"
                        },
                        new
                        {
                            CountryID = 324,
                            CountryName = "Guinea"
                        },
                        new
                        {
                            CountryID = 624,
                            CountryName = "Guinea-Bissau"
                        },
                        new
                        {
                            CountryID = 328,
                            CountryName = "Guyana"
                        },
                        new
                        {
                            CountryID = 332,
                            CountryName = "Haiti"
                        },
                        new
                        {
                            CountryID = 334,
                            CountryName = "Heard Island and McDonald Islands"
                        },
                        new
                        {
                            CountryID = 336,
                            CountryName = "Holy See"
                        },
                        new
                        {
                            CountryID = 340,
                            CountryName = "Honduras"
                        },
                        new
                        {
                            CountryID = 344,
                            CountryName = "Hong Kong"
                        },
                        new
                        {
                            CountryID = 348,
                            CountryName = "Hungary"
                        },
                        new
                        {
                            CountryID = 352,
                            CountryName = "Iceland"
                        },
                        new
                        {
                            CountryID = 356,
                            CountryName = "India"
                        },
                        new
                        {
                            CountryID = 360,
                            CountryName = "Indonesia"
                        },
                        new
                        {
                            CountryID = 364,
                            CountryName = "Iran, Islamic Republic of"
                        },
                        new
                        {
                            CountryID = 368,
                            CountryName = "Iraq"
                        },
                        new
                        {
                            CountryID = 372,
                            CountryName = "Ireland"
                        },
                        new
                        {
                            CountryID = 833,
                            CountryName = "Isle of Man"
                        },
                        new
                        {
                            CountryID = 376,
                            CountryName = "Israel"
                        },
                        new
                        {
                            CountryID = 380,
                            CountryName = "Italy"
                        },
                        new
                        {
                            CountryID = 388,
                            CountryName = "Jamaica"
                        },
                        new
                        {
                            CountryID = 392,
                            CountryName = "Japan"
                        },
                        new
                        {
                            CountryID = 832,
                            CountryName = "Jersey"
                        },
                        new
                        {
                            CountryID = 400,
                            CountryName = "Jordan"
                        },
                        new
                        {
                            CountryID = 398,
                            CountryName = "Kazakhstan"
                        },
                        new
                        {
                            CountryID = 404,
                            CountryName = "Kenya"
                        },
                        new
                        {
                            CountryID = 296,
                            CountryName = "Kiribati"
                        },
                        new
                        {
                            CountryID = 408,
                            CountryName = "Korea, Democratic People's Republic of"
                        },
                        new
                        {
                            CountryID = 410,
                            CountryName = "Korea, Republic of"
                        },
                        new
                        {
                            CountryID = 414,
                            CountryName = "Kuwait"
                        },
                        new
                        {
                            CountryID = 417,
                            CountryName = "Kyrgyzstan"
                        },
                        new
                        {
                            CountryID = 418,
                            CountryName = "Lao People's Democratic Republic"
                        },
                        new
                        {
                            CountryID = 428,
                            CountryName = "Latvia"
                        },
                        new
                        {
                            CountryID = 422,
                            CountryName = "Lebanon"
                        },
                        new
                        {
                            CountryID = 426,
                            CountryName = "Lesotho"
                        },
                        new
                        {
                            CountryID = 430,
                            CountryName = "Liberia"
                        },
                        new
                        {
                            CountryID = 434,
                            CountryName = "Libya"
                        },
                        new
                        {
                            CountryID = 438,
                            CountryName = "Liechtenstein"
                        },
                        new
                        {
                            CountryID = 440,
                            CountryName = "Lithuania"
                        },
                        new
                        {
                            CountryID = 442,
                            CountryName = "Luxembourg"
                        },
                        new
                        {
                            CountryID = 446,
                            CountryName = "Macao"
                        },
                        new
                        {
                            CountryID = 450,
                            CountryName = "Madagascar"
                        },
                        new
                        {
                            CountryID = 454,
                            CountryName = "Malawi"
                        },
                        new
                        {
                            CountryID = 458,
                            CountryName = "Malaysia"
                        },
                        new
                        {
                            CountryID = 462,
                            CountryName = "Maldives"
                        },
                        new
                        {
                            CountryID = 466,
                            CountryName = "Mali"
                        },
                        new
                        {
                            CountryID = 470,
                            CountryName = "Malta"
                        },
                        new
                        {
                            CountryID = 584,
                            CountryName = "Marshall Islands"
                        },
                        new
                        {
                            CountryID = 474,
                            CountryName = "Martinique"
                        },
                        new
                        {
                            CountryID = 478,
                            CountryName = "Mauritania"
                        },
                        new
                        {
                            CountryID = 480,
                            CountryName = "Mauritius"
                        },
                        new
                        {
                            CountryID = 175,
                            CountryName = "Mayotte"
                        },
                        new
                        {
                            CountryID = 484,
                            CountryName = "Mexico"
                        },
                        new
                        {
                            CountryID = 583,
                            CountryName = "Micronesia, Federated States of"
                        },
                        new
                        {
                            CountryID = 498,
                            CountryName = "Moldova, Republic of"
                        },
                        new
                        {
                            CountryID = 492,
                            CountryName = "Monaco"
                        },
                        new
                        {
                            CountryID = 496,
                            CountryName = "Mongolia"
                        },
                        new
                        {
                            CountryID = 499,
                            CountryName = "Montenegro"
                        },
                        new
                        {
                            CountryID = 500,
                            CountryName = "Montserrat"
                        },
                        new
                        {
                            CountryID = 504,
                            CountryName = "Morocco"
                        },
                        new
                        {
                            CountryID = 508,
                            CountryName = "Mozambique"
                        },
                        new
                        {
                            CountryID = 104,
                            CountryName = "Myanmar"
                        },
                        new
                        {
                            CountryID = 516,
                            CountryName = "Namibia"
                        },
                        new
                        {
                            CountryID = 520,
                            CountryName = "Nauru"
                        },
                        new
                        {
                            CountryID = 524,
                            CountryName = "Nepal"
                        },
                        new
                        {
                            CountryID = 528,
                            CountryName = "Netherlands"
                        },
                        new
                        {
                            CountryID = 540,
                            CountryName = "New Caledonia"
                        },
                        new
                        {
                            CountryID = 554,
                            CountryName = "New Zealand"
                        },
                        new
                        {
                            CountryID = 558,
                            CountryName = "Nicaragua"
                        },
                        new
                        {
                            CountryID = 562,
                            CountryName = "Niger"
                        },
                        new
                        {
                            CountryID = 566,
                            CountryName = "Nigeria"
                        },
                        new
                        {
                            CountryID = 570,
                            CountryName = "Niue"
                        },
                        new
                        {
                            CountryID = 574,
                            CountryName = "Norfolk Island"
                        },
                        new
                        {
                            CountryID = 580,
                            CountryName = "Northern Mariana Islands"
                        },
                        new
                        {
                            CountryID = 807,
                            CountryName = "North Macedonia"
                        },
                        new
                        {
                            CountryID = 578,
                            CountryName = "Norway"
                        },
                        new
                        {
                            CountryID = 512,
                            CountryName = "Oman"
                        },
                        new
                        {
                            CountryID = 586,
                            CountryName = "Pakistan"
                        },
                        new
                        {
                            CountryID = 585,
                            CountryName = "Palau"
                        },
                        new
                        {
                            CountryID = 275,
                            CountryName = "Palestine, State of"
                        },
                        new
                        {
                            CountryID = 591,
                            CountryName = "Panama"
                        },
                        new
                        {
                            CountryID = 598,
                            CountryName = "Papua New Guinea"
                        },
                        new
                        {
                            CountryID = 600,
                            CountryName = "Paraguay"
                        },
                        new
                        {
                            CountryID = 604,
                            CountryName = "Peru"
                        },
                        new
                        {
                            CountryID = 608,
                            CountryName = "Philippines"
                        },
                        new
                        {
                            CountryID = 612,
                            CountryName = "Pitcairn"
                        },
                        new
                        {
                            CountryID = 616,
                            CountryName = "Poland"
                        },
                        new
                        {
                            CountryID = 620,
                            CountryName = "Portugal"
                        },
                        new
                        {
                            CountryID = 630,
                            CountryName = "Puerto Rico"
                        },
                        new
                        {
                            CountryID = 634,
                            CountryName = "Qatar"
                        },
                        new
                        {
                            CountryID = 638,
                            CountryName = "Réunion"
                        },
                        new
                        {
                            CountryID = 642,
                            CountryName = "Romania"
                        },
                        new
                        {
                            CountryID = 643,
                            CountryName = "Russian Federation"
                        },
                        new
                        {
                            CountryID = 646,
                            CountryName = "Rwanda"
                        },
                        new
                        {
                            CountryID = 652,
                            CountryName = "Saint Barthélemy"
                        },
                        new
                        {
                            CountryID = 654,
                            CountryName = "Saint Helena, Ascension and Tristan da Cunha"
                        },
                        new
                        {
                            CountryID = 659,
                            CountryName = "Saint Kitts and Nevis"
                        },
                        new
                        {
                            CountryID = 662,
                            CountryName = "Saint Lucia"
                        },
                        new
                        {
                            CountryID = 663,
                            CountryName = "Saint Martin (French part)"
                        },
                        new
                        {
                            CountryID = 666,
                            CountryName = "Saint Pierre and Miquelon"
                        },
                        new
                        {
                            CountryID = 670,
                            CountryName = "Saint Vincent and the Grenadines"
                        },
                        new
                        {
                            CountryID = 882,
                            CountryName = "Samoa"
                        },
                        new
                        {
                            CountryID = 674,
                            CountryName = "San Marino"
                        },
                        new
                        {
                            CountryID = 678,
                            CountryName = "Sao Tome and Principe"
                        },
                        new
                        {
                            CountryID = 682,
                            CountryName = "Saudi Arabia"
                        },
                        new
                        {
                            CountryID = 686,
                            CountryName = "Senegal"
                        },
                        new
                        {
                            CountryID = 688,
                            CountryName = "Serbia"
                        },
                        new
                        {
                            CountryID = 690,
                            CountryName = "Seychelles"
                        },
                        new
                        {
                            CountryID = 694,
                            CountryName = "Sierra Leone"
                        },
                        new
                        {
                            CountryID = 702,
                            CountryName = "Singapore"
                        },
                        new
                        {
                            CountryID = 534,
                            CountryName = "Sint Maarten (Dutch part)"
                        },
                        new
                        {
                            CountryID = 703,
                            CountryName = "Slovakia"
                        },
                        new
                        {
                            CountryID = 705,
                            CountryName = "Slovenia"
                        },
                        new
                        {
                            CountryID = 90,
                            CountryName = "Solomon Islands"
                        },
                        new
                        {
                            CountryID = 706,
                            CountryName = "Somalia"
                        },
                        new
                        {
                            CountryID = 710,
                            CountryName = "South Africa"
                        },
                        new
                        {
                            CountryID = 239,
                            CountryName = "South Georgia and the South Sandwich Islands"
                        },
                        new
                        {
                            CountryID = 728,
                            CountryName = "South Sudan"
                        },
                        new
                        {
                            CountryID = 724,
                            CountryName = "Spain"
                        },
                        new
                        {
                            CountryID = 144,
                            CountryName = "Sri Lanka"
                        },
                        new
                        {
                            CountryID = 729,
                            CountryName = "Sudan"
                        },
                        new
                        {
                            CountryID = 740,
                            CountryName = "Suriname"
                        },
                        new
                        {
                            CountryID = 744,
                            CountryName = "Svalbard and Jan Mayen"
                        },
                        new
                        {
                            CountryID = 752,
                            CountryName = "Sweden"
                        },
                        new
                        {
                            CountryID = 756,
                            CountryName = "Switzerland"
                        },
                        new
                        {
                            CountryID = 760,
                            CountryName = "Syrian Arab Republic"
                        },
                        new
                        {
                            CountryID = 158,
                            CountryName = "Taiwan, Province of China"
                        },
                        new
                        {
                            CountryID = 762,
                            CountryName = "Tajikistan"
                        },
                        new
                        {
                            CountryID = 834,
                            CountryName = "Tanzania, United Republic of"
                        },
                        new
                        {
                            CountryID = 764,
                            CountryName = "Thailand"
                        },
                        new
                        {
                            CountryID = 626,
                            CountryName = "Timor-Leste"
                        },
                        new
                        {
                            CountryID = 768,
                            CountryName = "Togo"
                        },
                        new
                        {
                            CountryID = 772,
                            CountryName = "Tokelau"
                        },
                        new
                        {
                            CountryID = 776,
                            CountryName = "Tonga"
                        },
                        new
                        {
                            CountryID = 780,
                            CountryName = "Trinidad and Tobago"
                        },
                        new
                        {
                            CountryID = 788,
                            CountryName = "Tunisia"
                        },
                        new
                        {
                            CountryID = 792,
                            CountryName = "Turkey"
                        },
                        new
                        {
                            CountryID = 795,
                            CountryName = "Turkmenistan"
                        },
                        new
                        {
                            CountryID = 796,
                            CountryName = "Turks and Caicos Islands"
                        },
                        new
                        {
                            CountryID = 798,
                            CountryName = "Tuvalu"
                        },
                        new
                        {
                            CountryID = 800,
                            CountryName = "Uganda"
                        },
                        new
                        {
                            CountryID = 804,
                            CountryName = "Ukraine"
                        },
                        new
                        {
                            CountryID = 784,
                            CountryName = "United Arab Emirates"
                        },
                        new
                        {
                            CountryID = 826,
                            CountryName = "United Kingdom of Great Britain and Northern Ireland"
                        },
                        new
                        {
                            CountryID = 840,
                            CountryName = "United States of America"
                        },
                        new
                        {
                            CountryID = 581,
                            CountryName = "United States Minor Outlying Islands"
                        },
                        new
                        {
                            CountryID = 858,
                            CountryName = "Uruguay"
                        },
                        new
                        {
                            CountryID = 860,
                            CountryName = "Uzbekistan"
                        },
                        new
                        {
                            CountryID = 548,
                            CountryName = "Vanuatu"
                        },
                        new
                        {
                            CountryID = 862,
                            CountryName = "Venezuela, Bolivarian Republic of"
                        },
                        new
                        {
                            CountryID = 704,
                            CountryName = "Viet Nam"
                        },
                        new
                        {
                            CountryID = 92,
                            CountryName = "Virgin Islands, British"
                        },
                        new
                        {
                            CountryID = 850,
                            CountryName = "Virgin Islands, U.S."
                        },
                        new
                        {
                            CountryID = 876,
                            CountryName = "Wallis and Futuna"
                        },
                        new
                        {
                            CountryID = 732,
                            CountryName = "Western Sahara"
                        },
                        new
                        {
                            CountryID = 887,
                            CountryName = "Yemen"
                        },
                        new
                        {
                            CountryID = 894,
                            CountryName = "Zambia"
                        },
                        new
                        {
                            CountryID = 716,
                            CountryName = "Zimbabwe"
                        },
                        new
                        {
                            CountryID = 248,
                            CountryName = "Åland Islands"
                        });
                });

            modelBuilder.Entity("BookingProcessor.Models.Flight", b =>
                {
                    b.Property<int>("FlightID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AirlineID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArrivalAirportID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ArrivalDateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("BookedSeats")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DepartureAirportID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DepartureDateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("FlightCost")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxSeats")
                        .HasColumnType("INTEGER");

                    b.HasKey("FlightID");

                    b.ToTable("Flight");

                    b.HasData(
                        new
                        {
                            FlightID = 1,
                            AirlineID = 1,
                            ArrivalAirportID = 2,
                            ArrivalDateTime = new DateTime(2023, 11, 30, 16, 45, 56, 655, DateTimeKind.Local).AddTicks(9920),
                            BookedSeats = 50,
                            DepartureAirportID = 1,
                            DepartureDateTime = new DateTime(2023, 11, 29, 16, 45, 56, 655, DateTimeKind.Local).AddTicks(9917),
                            FlightCost = 500,
                            MaxSeats = 100
                        },
                        new
                        {
                            FlightID = 2,
                            AirlineID = 2,
                            ArrivalAirportID = 3,
                            ArrivalDateTime = new DateTime(2023, 12, 4, 16, 45, 56, 655, DateTimeKind.Local).AddTicks(9924),
                            BookedSeats = 30,
                            DepartureAirportID = 2,
                            DepartureDateTime = new DateTime(2023, 12, 2, 16, 45, 56, 655, DateTimeKind.Local).AddTicks(9923),
                            FlightCost = 450,
                            MaxSeats = 80
                        },
                        new
                        {
                            FlightID = 3,
                            AirlineID = 3,
                            ArrivalAirportID = 4,
                            ArrivalDateTime = new DateTime(2023, 12, 9, 16, 45, 56, 655, DateTimeKind.Local).AddTicks(9926),
                            BookedSeats = 70,
                            DepartureAirportID = 3,
                            DepartureDateTime = new DateTime(2023, 12, 7, 16, 45, 56, 655, DateTimeKind.Local).AddTicks(9925),
                            FlightCost = 600,
                            MaxSeats = 120
                        },
                        new
                        {
                            FlightID = 4,
                            AirlineID = 4,
                            ArrivalAirportID = 5,
                            ArrivalDateTime = new DateTime(2023, 12, 14, 16, 45, 56, 655, DateTimeKind.Local).AddTicks(9929),
                            BookedSeats = 40,
                            DepartureAirportID = 4,
                            DepartureDateTime = new DateTime(2023, 12, 12, 16, 45, 56, 655, DateTimeKind.Local).AddTicks(9928),
                            FlightCost = 550,
                            MaxSeats = 100
                        },
                        new
                        {
                            FlightID = 5,
                            AirlineID = 5,
                            ArrivalAirportID = 1,
                            ArrivalDateTime = new DateTime(2023, 12, 19, 16, 45, 56, 655, DateTimeKind.Local).AddTicks(9932),
                            BookedSeats = 60,
                            DepartureAirportID = 5,
                            DepartureDateTime = new DateTime(2023, 12, 17, 16, 45, 56, 655, DateTimeKind.Local).AddTicks(9931),
                            FlightCost = 480,
                            MaxSeats = 80
                        });
                });

            modelBuilder.Entity("BookingProcessor.Models.Hotel", b =>
                {
                    b.Property<int>("HotelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AddressLine1")
                        .HasColumnType("TEXT");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<int>("CountryID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HotelName")
                        .HasColumnType("TEXT");

                    b.Property<int>("PhoneNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Postcode")
                        .HasColumnType("TEXT");

                    b.Property<double>("Rating")
                        .HasColumnType("REAL");

                    b.Property<int>("RoomCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("HotelID");

                    b.ToTable("Hotel");

                    b.HasData(
                        new
                        {
                            HotelID = 1,
                            AddressLine1 = "123 Main St",
                            AddressLine2 = "Apt 45",
                            City = "Cityville",
                            CountryID = 826,
                            HotelName = "Example Hotel 1",
                            PhoneNumber = 5551234,
                            Postcode = "12345",
                            Rating = 4.0,
                            RoomCount = 50
                        },
                        new
                        {
                            HotelID = 2,
                            AddressLine1 = "456 Oak St",
                            AddressLine2 = "Suite 22",
                            City = "Townsville",
                            CountryID = 826,
                            HotelName = "Example Hotel 2",
                            PhoneNumber = 5555678,
                            Postcode = "67890",
                            Rating = 3.5,
                            RoomCount = 40
                        },
                        new
                        {
                            HotelID = 3,
                            AddressLine1 = "789 Pine St",
                            AddressLine2 = "Unit 33",
                            City = "Villagetown",
                            CountryID = 826,
                            HotelName = "Example Hotel 3",
                            PhoneNumber = 5559999,
                            Postcode = "10111",
                            Rating = 4.2000000000000002,
                            RoomCount = 60
                        },
                        new
                        {
                            HotelID = 4,
                            AddressLine1 = "101 Cedar St",
                            AddressLine2 = "Apt 10",
                            City = "Mountainview",
                            CountryID = 826,
                            HotelName = "Example Hotel 4",
                            PhoneNumber = 5554321,
                            Postcode = "54321",
                            Rating = 3.7999999999999998,
                            RoomCount = 45
                        },
                        new
                        {
                            HotelID = 5,
                            AddressLine1 = "202 Birch St",
                            AddressLine2 = "Suite 5",
                            City = "Laketown",
                            CountryID = 826,
                            HotelName = "Example Hotel 5",
                            PhoneNumber = 5551111,
                            Postcode = "87654",
                            Rating = 4.5,
                            RoomCount = 55
                        });
                });

            modelBuilder.Entity("BookingProcessor.Models.HotelBooking", b =>
                {
                    b.Property<int>("HotelBookingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CheckInDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CheckOutDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("HotelID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoomID")
                        .HasColumnType("INTEGER");

                    b.HasKey("HotelBookingID");

                    b.ToTable("HotelBooking");

                    b.HasData(
                        new
                        {
                            HotelBookingID = 1,
                            CheckInDate = new DateTime(2023, 11, 29, 16, 45, 56, 655, DateTimeKind.Local).AddTicks(9958),
                            CheckOutDate = new DateTime(2023, 12, 6, 16, 45, 56, 655, DateTimeKind.Local).AddTicks(9959),
                            HotelID = 1,
                            RoomID = 1
                        },
                        new
                        {
                            HotelBookingID = 2,
                            CheckInDate = new DateTime(2023, 12, 2, 16, 45, 56, 655, DateTimeKind.Local).AddTicks(9962),
                            CheckOutDate = new DateTime(2023, 12, 9, 16, 45, 56, 655, DateTimeKind.Local).AddTicks(9963),
                            HotelID = 2,
                            RoomID = 2
                        },
                        new
                        {
                            HotelBookingID = 3,
                            CheckInDate = new DateTime(2023, 12, 7, 16, 45, 56, 655, DateTimeKind.Local).AddTicks(9964),
                            CheckOutDate = new DateTime(2023, 12, 14, 16, 45, 56, 655, DateTimeKind.Local).AddTicks(9965),
                            HotelID = 3,
                            RoomID = 3
                        },
                        new
                        {
                            HotelBookingID = 4,
                            CheckInDate = new DateTime(2023, 12, 12, 16, 45, 56, 655, DateTimeKind.Local).AddTicks(9967),
                            CheckOutDate = new DateTime(2023, 12, 19, 16, 45, 56, 655, DateTimeKind.Local).AddTicks(9967),
                            HotelID = 4,
                            RoomID = 4
                        },
                        new
                        {
                            HotelBookingID = 5,
                            CheckInDate = new DateTime(2023, 12, 17, 16, 45, 56, 655, DateTimeKind.Local).AddTicks(9969),
                            CheckOutDate = new DateTime(2023, 12, 24, 16, 45, 56, 655, DateTimeKind.Local).AddTicks(9970),
                            HotelID = 5,
                            RoomID = 5
                        });
                });

            modelBuilder.Entity("BookingProcessor.Models.Insurance", b =>
                {
                    b.Property<int>("InsuranceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("InsuranceType")
                        .HasColumnType("TEXT");

                    b.Property<double>("PricePerDay")
                        .HasColumnType("REAL");

                    b.HasKey("InsuranceID");

                    b.ToTable("Insurance");

                    b.HasData(
                        new
                        {
                            InsuranceID = 1,
                            InsuranceType = "Basic",
                            PricePerDay = 10.5
                        },
                        new
                        {
                            InsuranceID = 2,
                            InsuranceType = "Standard",
                            PricePerDay = 15.75
                        },
                        new
                        {
                            InsuranceID = 3,
                            InsuranceType = "Premium",
                            PricePerDay = 20.0
                        },
                        new
                        {
                            InsuranceID = 4,
                            InsuranceType = "Extended",
                            PricePerDay = 25.5
                        },
                        new
                        {
                            InsuranceID = 5,
                            InsuranceType = "Deluxe",
                            PricePerDay = 30.0
                        });
                });

            modelBuilder.Entity("BookingProcessor.Models.InsuranceBooking", b =>
                {
                    b.Property<int>("InsuranceBookingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("InsuranceID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("InsuranceBookingID");

                    b.ToTable("InsuranceBooking");

                    b.HasData(
                        new
                        {
                            InsuranceBookingID = 1,
                            EndDate = new DateTime(2023, 12, 6, 16, 45, 56, 655, DateTimeKind.Local).AddTicks(9991),
                            InsuranceID = 1,
                            StartDate = new DateTime(2023, 11, 29, 16, 45, 56, 655, DateTimeKind.Local).AddTicks(9989)
                        },
                        new
                        {
                            InsuranceBookingID = 2,
                            EndDate = new DateTime(2023, 12, 9, 16, 45, 56, 655, DateTimeKind.Local).AddTicks(9993),
                            InsuranceID = 2,
                            StartDate = new DateTime(2023, 12, 2, 16, 45, 56, 655, DateTimeKind.Local).AddTicks(9992)
                        },
                        new
                        {
                            InsuranceBookingID = 3,
                            EndDate = new DateTime(2023, 12, 14, 16, 45, 56, 655, DateTimeKind.Local).AddTicks(9995),
                            InsuranceID = 3,
                            StartDate = new DateTime(2023, 12, 7, 16, 45, 56, 655, DateTimeKind.Local).AddTicks(9994)
                        },
                        new
                        {
                            InsuranceBookingID = 4,
                            EndDate = new DateTime(2023, 12, 19, 16, 45, 56, 655, DateTimeKind.Local).AddTicks(9998),
                            InsuranceID = 4,
                            StartDate = new DateTime(2023, 12, 12, 16, 45, 56, 655, DateTimeKind.Local).AddTicks(9997)
                        },
                        new
                        {
                            InsuranceBookingID = 5,
                            EndDate = new DateTime(2023, 12, 24, 16, 45, 56, 656, DateTimeKind.Local).AddTicks(1),
                            InsuranceID = 5,
                            StartDate = new DateTime(2023, 12, 17, 16, 45, 56, 656, DateTimeKind.Local)
                        });
                });

            modelBuilder.Entity("BookingProcessor.Models.Room", b =>
                {
                    b.Property<int>("RoomID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("HotelID")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PricePerNight")
                        .HasColumnType("TEXT");

                    b.Property<int>("RoomNo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoomType")
                        .HasColumnType("TEXT");

                    b.HasKey("RoomID");

                    b.ToTable("Room");

                    b.HasData(
                        new
                        {
                            RoomID = 1,
                            HotelID = 1,
                            PricePerNight = 100m,
                            RoomNo = 101,
                            RoomType = "Standard"
                        },
                        new
                        {
                            RoomID = 2,
                            HotelID = 2,
                            PricePerNight = 150m,
                            RoomNo = 201,
                            RoomType = "Deluxe"
                        },
                        new
                        {
                            RoomID = 3,
                            HotelID = 3,
                            PricePerNight = 200m,
                            RoomNo = 301,
                            RoomType = "Suite"
                        },
                        new
                        {
                            RoomID = 4,
                            HotelID = 4,
                            PricePerNight = 110m,
                            RoomNo = 102,
                            RoomType = "Standard"
                        },
                        new
                        {
                            RoomID = 5,
                            HotelID = 5,
                            PricePerNight = 180m,
                            RoomNo = 202,
                            RoomType = "Suite"
                        });
                });

            modelBuilder.Entity("BookingProcessor.Models.Vehicle", b =>
                {
                    b.Property<int>("VehicleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PricePerDay")
                        .HasColumnType("TEXT");

                    b.Property<string>("VehicleType")
                        .HasColumnType("TEXT");

                    b.HasKey("VehicleID");

                    b.ToTable("Vehicle");

                    b.HasData(
                        new
                        {
                            VehicleID = 1,
                            PricePerDay = 45.0m,
                            VehicleType = "Compact Car"
                        },
                        new
                        {
                            VehicleID = 2,
                            PricePerDay = 60.0m,
                            VehicleType = "SUV"
                        },
                        new
                        {
                            VehicleID = 3,
                            PricePerDay = 75.0m,
                            VehicleType = "Van"
                        },
                        new
                        {
                            VehicleID = 4,
                            PricePerDay = 100.0m,
                            VehicleType = "Luxury Car"
                        },
                        new
                        {
                            VehicleID = 5,
                            PricePerDay = 30.0m,
                            VehicleType = "Motorcycle"
                        });
                });

            modelBuilder.Entity("BookingProcessor.Models.VehicleBooking", b =>
                {
                    b.Property<int>("VehicleBookingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DropOffDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PickUpDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("VehicleID")
                        .HasColumnType("INTEGER");

                    b.HasKey("VehicleBookingID");

                    b.ToTable("VehicleBooking");

                    b.HasData(
                        new
                        {
                            VehicleBookingID = 1,
                            DropOffDate = new DateTime(2023, 12, 6, 16, 45, 56, 656, DateTimeKind.Local).AddTicks(33),
                            PickUpDate = new DateTime(2023, 11, 29, 16, 45, 56, 656, DateTimeKind.Local).AddTicks(32),
                            VehicleID = 1
                        },
                        new
                        {
                            VehicleBookingID = 2,
                            DropOffDate = new DateTime(2023, 12, 9, 16, 45, 56, 656, DateTimeKind.Local).AddTicks(36),
                            PickUpDate = new DateTime(2023, 12, 2, 16, 45, 56, 656, DateTimeKind.Local).AddTicks(35),
                            VehicleID = 2
                        },
                        new
                        {
                            VehicleBookingID = 3,
                            DropOffDate = new DateTime(2023, 12, 14, 16, 45, 56, 656, DateTimeKind.Local).AddTicks(38),
                            PickUpDate = new DateTime(2023, 12, 7, 16, 45, 56, 656, DateTimeKind.Local).AddTicks(37),
                            VehicleID = 3
                        },
                        new
                        {
                            VehicleBookingID = 4,
                            DropOffDate = new DateTime(2023, 12, 19, 16, 45, 56, 656, DateTimeKind.Local).AddTicks(40),
                            PickUpDate = new DateTime(2023, 12, 12, 16, 45, 56, 656, DateTimeKind.Local).AddTicks(39),
                            VehicleID = 4
                        },
                        new
                        {
                            VehicleBookingID = 5,
                            DropOffDate = new DateTime(2023, 12, 24, 16, 45, 56, 656, DateTimeKind.Local).AddTicks(43),
                            PickUpDate = new DateTime(2023, 12, 17, 16, 45, 56, 656, DateTimeKind.Local).AddTicks(42),
                            VehicleID = 5
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
